# Generated by Django 4.0.1 on 2022-01-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_client_adress_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
